# Generated by Django 3.2.22 on 2023-11-10 16:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_recipedetail_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipeimage',
            field=cloudinary.models.CloudinaryField(default='place_holder', max_length=255, verbose_name='image'),
        ),
    ]
