# Generated by Django 3.2.22 on 2023-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_recipes_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='content_header',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
