# Generated by Django 3.2.22 on 2023-12-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_recipes_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fetaured_image',
            new_name='featured_image',
        ),
    ]
