# Generated by Django 3.2.22 on 2024-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20240206_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='place_holder'),
        ),
        migrations.DeleteModel(
            name='RecipeDetail',
        ),
    ]
